### ISSUE TITLE
Crash when closing a floating dock window which has a maximised dock item inside it

### ISSUE THREAD

**Issue by e-calder** [nucleic/enaml#467] opened 2022-01-04 16:12 UTC
Hey, 

I've noticed a crash related to maximised floating windows within a group... to reproduce:

1) Run `examples/widgets/dock_area.enaml`
2) Drag out 2 or more dock items so they are floating, and group them into their own floating dock window (terminology might not be accurate, please excuse)

![Enaml1](https://user-images.githubusercontent.com/37456137/148088432-36394431-9608-4d53-9846-5dfc4f4d3a6d.png)

3) **Maximise** one of these dock items within the dock window, then close the dock window via the outer red cross (circled).

![Enaml2](https://user-images.githubusercontent.com/37456137/148088559-d58e76cc-821c-4e8d-b3d8-35d45695ab47.png)

4) This results in a hard crash, killing the application: 

```
Traceback (most recent call last):
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\qt\q_deferred_caller.py", line 43, in customEvent
    event.callback(*event.args, **event.kwargs)
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\widgets\toolkit_object.py", line 169, in destroy
    super(ToolkitObject, self).destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\styling.py", line 298, in destroy
    super(Stylable, self).destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\core\declarative.py", line 128, in destroy
    super(Declarative, self).destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\core\object.py", line 114, in destroy
    child.destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\widgets\toolkit_object.py", line 169, in destroy
    super(ToolkitObject, self).destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\styling.py", line 298, in destroy
    super(Stylable, self).destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\core\declarative.py", line 128, in destroy
    super(Declarative, self).destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\core\object.py", line 114, in destroy
    child.destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\widgets\toolkit_object.py", line 172, in destroy
    self.proxy.destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\qt\qt_constraints_widget.py", line 46, in destroy
    super(QtConstraintsWidget, self).destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\qt\qt_widget.py", line 95, in destroy
    super(QtWidget, self).destroy()
  File "c:\users\ecalder\code\virtualenvs\bc-env\lib\site-packages\enaml\qt\qt_toolkit_object.py", line 93, in destroy
    widget.setParent(None)
RuntimeError: wrapped C/C++ object of type QTextEdit has been deleted
```

Thanks in advance!

Emy

**Comment by frmdstryr** [comment] 2022-01-04 16:52
I'm able to reproduce it here... 

Does it make sense to check if the handle is valid or is there a better way to do that? 

Eg, this fixes that particular case https://github.com/nucleic/enaml/commit/c21605ac2348495627e38f004f11791262f3329c

**Comment by MatthieuDartiailh** [comment] 2022-01-04 17:23
Thanks for reproducing @frmdstryr. I will investigate but enaml should prevent the need to explicitly checking the widget state.

**Comment by MatthieuDartiailh** [comment] 2022-01-07 19:00
Since I am not sure when I will time to dive deep enough to figure this out, I will spell a bit my guesses regarding what may be happening in case somebody else wants to have a look.

Typically enaml will have the backend (Qt) forward any closing request to the front-end (Enaml widget) which ensures that the back-end does not disappear without the front-end not knowing about it. However in this issue it is typically what happens.

My best guess is that in the case of floating dock-window which are not backed by an actual enaml widget part of that logic fails when multiple dock-items are involved. Actually I think it would be worthwhile checking if vetoing the closing of a floating dock-item works at all and if it works hen multiple items belong to the same window. This is likely the easiest way to check if the front-end get the messages as it should. The relevant parts are under enaml/qt/docking, I think that the dock_manager, q_dock_window and q_dock_container are the most likely to be relevant.

**Comment by bburan** [comment] 2022-04-06 19:25
This seems to have been fixed. I attempted to replicate the crash but could not. Should we close this issue?

**Closed** 2022-04-07 00:33 UTC
